# sweeps/spice_bandit_v5.yaml
program: spice/train_spice.py
method: bayes

metric:
  # use the posterior controller as early objective (more stable than TS during early training)
  name: sanity/micro_regret_post_vs_dpt
  goal: minimize

parameters:
  # Fixed dataset / env
  env:        { value: bandit }
  envs:       { value: 100000 }
  H:          { value: 500 }
  dim:        { value: 5 }
  var:        { value: 0.3 }
  cov:        { value: 0.0 }
  hists:      { value: 1 }
  samples:    { value: 1 }
  wandb:      { value: true }

  # Model backbone
  layer:      { values: [4] }
  head:       { values: [1] }
  embd:       { values: [64] }
  dropout:    { values: [0.0] }

  # Optim
  lr:         { values: [0.0001] }
  num_epochs: { value: 300 }
  seed:       { values: [0, 1, 2] }
  shuffle:    { values: [true] }

  # SPICE hyper-params (enable ensemble diversity)
  spice_heads:   { values: [7, 10, 15] }
  spice_prior:   { values: [0.02, 0.05, 0.1] }
  alphaA:        { values: [0.5] }
  lambda_sigma:  { values: [0.25, 0.5, 1.0] }
  c_sigma:       { values: [3.0] }
  lambda_q:      { values: [1.0, 2.0] }
  lambda_var:    { values: [0.0] }          # keep OFF to preserve diversity
  bootstrap_p:   { values: [0.7, 0.8, 0.9] }
  lambda_anchor: { values: [0.0, 0.0003, 0.001] }

  # Policy–value alignment (disable initially)
  lambda_align:  { values: [0.0] }
  align_tau:     { values: [1.0] }

  # IS stabilizers
  is_laplace:    { values: [1.0] }
  is_cap:        { values: [10.0, 15.0, 20.0] }

  # Save dir
  models_dir:    { value: models_new }

  # DPT baseline path for micro-probe
  dpt_ckpt:
    value: /home/mila/a/anaisb/scratch/SPICE-toyenvs/models_notperhead/bandit_shufTrue_lr0.0001_do0.0_embd64_layer6_head1_envs100000_hists1_samples1_var0.3_cov0.0_H500_d5_seed0_epoch300.pt

  micro_probe_every:  { value: 10 }
  micro_probe_H:      { value: 200 }
  micro_probe_n_eval: { value: 16 }

early_terminate:
  type: hyperband
  min_iter: 60
  eta: 3
